import smokeTest from '../MoveMed.fixtures';
import AdminDashView from './AdminDashView/AdminDashView';
import ClientDashView from './ClientDashView/ClientDashView';
import ClientSelect from './ClientSelect/ClientSelect';
import Comment from './Comment/Comment';
import CommentsSection from './CommentsSection/CommentsSection';
import EditExerciseForm from './EditExerciseForm/EditExerciseForm';
import ExerciseItem from './ExerciseItem/ExerciseItem';
import ExerciseSelect from './ExerciseSelect/ExerciseSelect';
import ExerciseVidAndImg from './ExerciseVidAndImg/ExerciseVidAndImg';
import Footer from './Footer/Footer';
import Header from './Header/Header';
import LoginForm from './LoginForm/LoginForm';
import ProviderDashView from './ProviderDashView/ProviderDashView';
import SubmitCommentForm from './SubmitCommentForm/SubmitCommentForm';
import UserGoal from './UserGoal/UserGoal';
import UserItem from './UserItem/UserItem';

smokeTest('AdminDashView', <AdminDashView/>);
smokeTest('ClientDashView', <ClientDashView/>);
smokeTest('ClientSelect', <ClientSelect/>);
smokeTest('Comment', <Comment/>);
smokeTest('CommentsSection', <CommentsSection/>);
smokeTest('EditExerciseForm', <EditExerciseForm/>);
smokeTest('ExerciseItem', <ExerciseItem/>);
smokeTest('ExerciseSelect', <ExerciseSelect/>);
smokeTest('ExerciseVidAndImg', <ExerciseVidAndImg/>);
smokeTest('Footer', <Footer/>);
smokeTest('Header', <Header/>);
smokeTest('LoginForm', <LoginForm/>);
smokeTest('ProviderDashView', <ProviderDashView/>);
smokeTest('SubmitCommentForm', <SubmitCommentForm/>);
smokeTest('UserGoal', <UserGoal/>);
smokeTest('UserItem', <UserItem/>);